#!/bin/bash

# TODO: Change 'username' !!!
username="aw"

while true; do
    # Read content from 'input.dat' file in Documents directory
    input=$(cat /home/$username/Documents/input.dat)
    # Check if the input is a valid number
    if [[ $input =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
        # Compute the square using 'bc' with 4 decimal places
        result=$(echo "scale=4; $input*$input" | bc)
        # Save the result to 'result.dat' file in Documents directory
        echo $result > /home/$username/Documents/result.dat
    else
        echo "Invalid input in input.dat: $input"
    fi

    # Wait for 1 second
    sleep 1
done
